name: Debug
on:
  pull_request:
    types: [opened, synchronize, closed]
jobs:
  output-debug:
    runs-on: ubuntu-18.04
    steps:
      - uses: pavanbellamkonda/github-action-explore-debug@main
        with:
          args: .pull_request
